### ISSUE TITLE
backslash escapes are preserved in arguments

### ISSUE THREAD

**Issue by reduzent** [pd-externals/command#1]
Escape characters should be removed before symbols are passed to command.

**Comment by reduzent** [comment]
Is this a bug in [command] or a bug in Pd?

**Comment by umlaeute** [comment]
it's a bug in `[command]`.

the underlying problem is, that Pd does not provide an API call to convert any atom to a string that does not also escape spaces.

see also https://github.com/pure-data/pure-data/issues/1310
