### ISSUE TITLE
clarify that `[command]` runs asynchronously

### ISSUE THREAD

**Issue by umlaeute** [pd-externals/command#13]
command forks of the command to execute, so Pd can continue to do it's thing while the command runs. nice.

however, i think this needs to be documented more explicitly.

so far the only thing in the help-patch that deals with this topic is a single sentence saying:

> long running commands are not blocking

i think the "long" is misleading, as the blocking behavior is the same for short-running and long-running commands.
so probably "running commands are not blocking Pd" would be better.

also, the documentation should make it explicit that the output of `[command]` will break order of execution.

the following will always output the return code of the *previous* command (so on first run it will output `0`)
~~~
|
[t b b]
|     [exec false(
|     [command]
|int  ]
|
~~~

**Comment by reduzent** [comment]
Valid point. I added a section (see 2d3290eebce517e597a2509c7b0c48c7d4fc0c06) that explains some specifics of the [command] external and how it breaks some concepts of Pd usage (order of execution) and how it differs from calling commands with a terminal. Feel free to to adjust or comment.

**Comment by reduzent** [comment]
I think this is sufficiently addressed now.
