### ISSUE TITLE
Allow blocking mode

### ISSUE THREAD

**Issue by reduzent** [pd-externals/command#17]
It might be desirable in some situations to run [command] in blocking mode, so that order of execution is maintained, even if there is a [command] in the chain. Maybe this could be done with a flag `-d` (depth-first?) . 

```
[loadbang]
|
[t b b]
|     |
|     [exec date (
|     |
|     [command  -d]
|  /
[print]
```

Would yield:

```
print: Do 24 Nov 2022 11:10:24 CET
print: bang
```

**Comment by umlaeute** [comment]
`-d` doesn't look very memorable to me.

**Comment by reduzent** [comment]
Yeah, the only memorable thing that comes to me is `-b`, which is already taken. I'm open for suggestions. Memorable or not, I tend to find one character flags nice. Would you rather go for something like `-blocking`?

**Comment by reduzent** [comment]
And: do you think such a feature would be worthwhile at all?

**Comment by reduzent** [comment]
I went for `-s`: synchronous operation.
