### ISSUE TITLE
stderr and stdout outlets do not work reliably

### ISSUE THREAD

**Issue by reduzent** [pd-externals/command#2]
Depending on used audio backend, reliability is better or worse. Definitely much worse with JACK.

**Comment by umlaeute** [comment]
could you provide some examples of what you mean by this?

e.g. with the help patch's

~~~pd
[exec pwd(
|
[command]
|   |   |
    |
    [print STDOUT]
~~~

and JACK-audio (probably with DSP turned ON), i would only get printouts every second time i click on the msgbox.

Of course, I cannot reproduce this right now...

**Comment by reduzent** [comment]
Currently, I get nothing at all when clicking on `[exec pwd(` in the example above. `ls` doesn't return anythying to the stdout outlet, but `ls -lh command-help.pd` sometimes outputs something, sometimes not. 

I copied the `sys_addpollfn()` stuff from the original `[shell]` external which `[command]` is based on and I am not sure if I am using it correctly or whether the problem is related to its usage at all. 

@umlaeute: Anyway, thanks for your fixes. I learn a lot (or at least I hope I do). It's new territory for me.

**Comment by reduzent** [comment]
With a Pd build from git using tag `0.51-4`, I do get output to the stdout outlet in most cases. However, with most recent commit from master (248608dd), output to stdout or stderr outlets is suppressed most of the time.

**Comment by reduzent** [comment]
It seems `command_check()`  executes `command_cleanup()` too early. When increasing `x->x_del` to 100, the output isn't suppressed anymore.

**Comment by umlaeute** [comment]
i think the 100ms are bad, as you are basically hiding a synchronisation problem by buffering.

while this might work fine on your system, it might not work on other systems (e.g. higher load, smaller (or bigger!) audio buffer,...)

**Comment by reduzent** [comment]
Yeah, absolutely. The test with larger delay was for me a way to confirm, that there is indeed a synchronization problem. The actual fix in `command_check` is when it detects the command has exited, it polls the pipes for available data and prints it before `command_cleanup` is executed.
