### ISSUE TITLE
leading tabs from command output are discarded

### ISSUE THREAD

**Issue by reduzent** [pd-externals/command#3]
Commands like `jack_lsp` use leading tabs to distinguish between ports and what ports they are connected to.

**Comment by umlaeute** [comment]
i'm not entirely sure whether this is really an issue of `[command]`.

one could argue, that to make sense of a command-output, it has to be *machine-readable*, and having to parse whitespace is not really machine-readable.

otoh, probably adding a `-b` flag to `[command]` for *binary* output (just like with `[netreceive]`) is simple enough and shifts the problem to the patch.

**Comment by reduzent** [comment]
Yeah,  I thought about binary output, too. Sounds reasonable for cases that don't work well with FUDI.

**Comment by reduzent** [comment]
I turned this into a feature request:  #4
