### ISSUE TITLE
regression: 'send' method sends garbage

### ISSUE THREAD

**Issue by reduzent** [pd-externals/command#7]
6eed98d introduced a new problem to the `send` method. Its output looks like it is using uninitialized memory.

How to reproduce.

1. run `nc -l -n -p 8000` in a terminal
2. send `exec nc localhost 8000` to  `[command]`
3. send `send one two three four five` to `[command]`

What I get in the terminal:

```
��[l�one two three four jn5Vfive
```

What I would expect:

```
one two three four five
```

**Comment by umlaeute** [comment]
fixed with a292bcb
